### PR TITLE
Add contrib page and license

### PR DESCRIPTION
**Pull request by evilnick**
-  added Contributing page
-  added LICENSE
-  fixed a few minor issues in the readme

### CODE REVIEW

**Comment by evilnick** [comment]
I believe python 3.5 is out of pip support now, so may want to update the tests

**Comment by johnsca** [comment]
Don't we need to maintain 3.5 support until Xenial support is dropped?  That will be fun.

**Review by johnsca — APPROVED** [review]
The py35 test failure isn't due to the deprecation but it's also not related to this change.  I don't think we should block this on that failure; I'll file a separate bug for that.

**Comment by johnsca** [comment]
Filed [lp:1914073](https://bugs.launchpad.net/charm-easyrsa/+bug/1914073) for the test failure.

**Pull request merged**
